Shows._simpleSchema._messages = {
  required: "[label] wird benötigt",
  minString: "[label] muss mindestens [min] Zeichen lang sein",
  maxString: "[label] darf nicht mehr als [max] Zeichen lang sein",
  minNumber: "[label] muss mindestens [min] sein",
  maxNumber: "[label] darf nicht [max] überschreiten",
  minDate: "[label] muss vor dem oder an dem [min] sein",
  maxDate: "[label] darf nicht nach dem [max] sein",
  minCount: "Du musst mindestens [minCount] Werte angeben",
  maxCount: "Du darfst nicht mehr als [maxCount] Werte angeben",
  noDecimal: "[label] muss eine Zahl sein",
  notAllowed: "[value] ist nicht als Wert zugelassen",
  expectedString: "[label] muss eine Zeichenfolge sein",
  expectedNumber: "[label] muss eine Nummer sein",
  expectedBoolean: "[label] muss boolesch sein",
  expectedArray: "[label] muss ein Array sein",
  expectedObject: "[label] muss ein Objekt sein",
  expectedConstructor: "[label] muss ein [type] sein",
  regEx: "[label] entspricht nicht dem geforderten Schema"
};